---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aeron-cluster
spec:
  template:
    metadata:
      annotations:
        # These are required so dpdk-endpoint-slice-handler creates the corresponding EndpointSlices for each pod.
        dpdk/service-name: aeron-benchmark
        dpdk/port: "1000"
        dpdk/protocol: UDP
    spec:
      containers:
        - name: aeronmd-dpdk
          image: "< Ref to Aeron DPDK media driver container >"
        - name: aeron-cluster-node
          image: "< Ref to benchmark container >"
