---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-cluster-client
  labels:
    app.kubernetes.io/component: aeron-client
spec:
  containers:
    - name: aeronmd-dpdk
      imagePullPolicy: Always
      args:
        - "--no-telemetry"
        - "/opt/aeron-benchmarks/scripts/aeron/low-latency-driver.properties"
      securityContext:
        capabilities:
          # Required for DPDK
          add:
            - IPC_LOCK
            - SYS_RAWIO
            - SYS_ADMIN
      envFrom:
        - configMapRef:
            name: aeron-benchmark-dpdk
      resources:
        limits:
          cpu: "8"
          memory: 8G
          # Give us a DPDK NIC through https://github.com/AdaptiveConsulting/k8s-dpdk-mgr
          intel.com/aws_dpdk: "1"
      volumeMounts:
        - name: hugepage-2mi
          mountPath: /hugepages-2Mi
        - name: shm
          mountPath: /dev/shm
        - name: low-latency-properties-volume
          mountPath: /opt/aeron-benchmarks/scripts/aeron/low-latency-driver.properties
          subPath: low-latency-driver.properties
    - name: aeron-cluster-client
      env:
        - name: BENCHMARK_TYPE
          value: "aeron-cluster-dpdk"
      command:
        - "k8s/k8s-aeron-cluster-client.sh"
      args:
        - "--output-file"
        - "clusterclientdpdk"
        - "--message-rate"
        - "100K"
        - "--message-length"
        - "288"
        - "--iterations"
        - "60"
