---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-cluster-client
spec:
  containers:
    - name: aeronmd-dpdk
      image: "< Ref to Aeron DPDK media driver container >"
    - name: aeron-cluster-client
      image: "< Ref to benchmark container >"
      command: ["k8s/k8s-aeron-cluster-client.sh"]
      args:
        - "--output-file"
        - "cluster_dpdk_source=caf"
        - "--message-rate"
        - "101K"
        - "--message-length"
        - "288"
        - "--iterations"
        - "60"
