---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aeron-cluster
  labels:
    app.kubernetes.io/component: aeron-cluster
spec:
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/component: aeron-cluster
  volumeClaimTemplates:
    - metadata:
        name: data-volume-claim
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: io2
        resources:
          requests:
            storage: 100Gi
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: aeron-cluster
    spec:
      serviceAccountName: aeron-benchmark-sa
      tolerations:
        - key: perftest # Select our special benchmark nodes
          operator: Exists
      nodeSelector:
        weareadaptive.com/nodegroup: perftest # Select our special benchmark nodes
      volumes:
        - name: hugepage-2mi
          emptyDir:
            medium: HugePages-2Mi
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: aeron-properties
          configMap:
            name: aeron-properties
            items:
              - key: node.properties
                path: node.properties
              - key: cluster.properties
                path: cluster.properties
              - key: benchmark.properties
                path: benchmark.properties
              - key: low-latency-driver.properties
                path: low-latency-driver.properties
        - name: aeronmd-config # This volume holds the configuration generated by the aeron-bootstrap initcontainer
          emptyDir: {}
      containers:
        - name: aeron-cluster-node
          imagePullPolicy: Always
          command:
            - /opt/aeron-benchmarks/scripts/k8s/k8s-aeron-cluster-node.sh
          args:
            - /opt/aeron-config/cluster.properties
            - /opt/aeron-config/node.properties
          envFrom:
            - configMapRef:
                name: aeron-benchmark-envs
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          volumeMounts:
            - mountPath: /hugepages-2Mi
              name: hugepage-2mi
            - mountPath: /dev/shm
              name: shm
            - name: aeron-properties
              mountPath: /opt/aeron-config/node.properties
              subPath: node.properties
            - name: aeron-properties
              mountPath: /opt/aeron-config/cluster.properties
              subPath: cluster.properties
            - name: data-volume-claim
              mountPath: /aeron-data
          resources:
            requests:
              cpu: '11' # caters for pinning each aeron cluster thread to a physical CPU core
              memory: 8G
              hugepages-2Mi: 1Gi
            limits:
              cpu: '11' # caters for pinning each aeron cluster thread to a physical CPU core
              memory: 8G
              hugepages-2Mi: 1Gi

        - name: results
          image: public.ecr.aws/docker/library/busybox:stable
          command:
            - "sleep"
            - "infinity"
          envFrom:
            - configMapRef:
                name: aeron-benchmark-envs
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
          resources:
            # Must set limits, as whole Pod must have requests = limits to get into Guarenteed QoS class
            limits:
              cpu: "256m"
              memory: 512Mi
---
# Permission to look up Pod details
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aeron-benchmark
rules:
  # Allow reading pods to find bootstrap neighbors
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
---
# Serviceaccount for aeron-k8s-bootstrap to run under
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-benchmark-sa
---
# Bind the previously created role to the aeron-k8s-bootstrap service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aeron-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aeron-benchmark
subjects:
  - kind: ServiceAccount
    name: aeron-benchmark-sa
