---
# Update tolerations and nodeselectors
apiVersion: v1
kind: Pod
metadata:
  name: all
spec:
  containers:
    - name: aeronmd-dpdk
      image: "195275652846.dkr.ecr.eu-west-1.amazonaws.com/aeronmd-dpdk:017e81aa45004fed04b58e062e7a27eb70e516f3"
      resources:
        limits:
          # Give us a DPDK NIC through https://github.com/AdaptiveConsulting/k8s-dpdk-mgr
          intel.com/aws_dpdk: "1"
