---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aeron-cluster
spec:
  template:
    spec:
      initContainers:
        - name: aeron-bootstrap
          image: "< Ref to aeron-bootstrap container >"
      containers:
        - name: aeronmd-java
          image: "< Ref to benchmark container >"
        - name: aeron-cluster-node
          image: "< Ref to benchmark container >"
