---
apiVersion: v1
kind: StatefulSet
metadata:
  name: aeron-cluster-node
  labels:
    aeronmd: c
spec:
  template:
    spec:
      containers:
        - name: aeronmd-c
          image: "195275652846.dkr.ecr.eu-west-1.amazonaws.com/aeron-benchmarks:bds"
          imagePullPolicy: Always
          command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-c-media-driver.sh"]
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
          resources:
            limits:
              cpu: "8"
              memory: 8G
        - name: aeron-cluster-node
          env:
            - name: BENCHMARK_TYPE
              value: "aeron-cluster-c"
