---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aeron-cluster
  labels:
    aeronmd: c
spec:
  template:
    metadata:
      # Additional multus network
      annotations:
        k8s.v1.cni.cncf.io/networks: aeron-network
      labels:
        aeron.io/media-driver: "true" # needed by the aeron-bootstrap initcontainer to identify it as a media driver pod
    spec:
      initContainers:
        - name: aeron-bootstrap
          # Don't pull, as we pre-build/pre-load the images for CI
          imagePullPolicy: Always
          env:
            # example config to alter discovery process goes here
            - name: AERON_MD_DISCOVERY_PORT
              value: "8050"
            - name: AERON_MD_BOOTSTRAP_PATH
              value: /opt/aeronmd-config/bootstrap.properties
          volumeMounts:
            - name: aeronmd-config
              mountPath: /opt/aeronmd-config
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 256Mi
      containers:
        - name: aeronmd-c
          imagePullPolicy: Always
          command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-c-media-driver.sh"]
          args:
            - /opt/aeronmd-config/bootstrap.properties
            - /opt/aeron-config/low-latency-driver.properties
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: aeronmd-config
              mountPath: /opt/aeronmd-config
            - name: aeron-properties
              mountPath: /opt/aeron-config/low-latency-driver.properties
              subPath: low-latency-driver.properties
          resources:
            requests:
              cpu: "8"
              memory: 8G
            limits:
              cpu: "8"
              memory: 8G
        - name: aeron-cluster-node
          env:
            - name: BENCHMARK_TYPE
              value: "aeron-cluster-c"
