---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aeron-cluster
  labels:
    aeronmd: c
spec:
  template:
    metadata:
      # Additional multus network
      annotations:
        k8s.v1.cni.cncf.io/networks: aeron-network
    spec:
      containers:
        - name: aeronmd-c
          imagePullPolicy: Always
          command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-c-media-driver.sh"]
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
          resources:
            requests:
              cpu: "8"
              memory: 8G
            limits:
              cpu: "8"
              memory: 8G
        - name: aeron-cluster-node
          env:
            - name: BENCHMARK_TYPE
              value: "aeron-cluster-c"
