---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-cluster-client
  labels:
    app.kubernetes.io/component: aeron-client
  # Additional multus network
  annotations:
    k8s.v1.cni.cncf.io/networks: aeron-network
    aeron.io/media-driver: "true"
spec:
  containers:
    - name: aeronmd-java
      imagePullPolicy: Always
      command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-java-media-driver.sh"]
      args:
        - /opt/aeron-md-config/bootstrap.properties
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: aeron-md-config-dir
          mountPath: /opt/aeron-md-config
      resources:
        requests:
          cpu: "8"
          memory: 8G
        limits:
          cpu: "8"
          memory: 8G
    - name: aeron-cluster-client
      env:
        - name: BENCHMARK_TYPE
          value: "aeron-cluster-java"
      command:
        - "k8s/k8s-aeron-cluster-client.sh"
