---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-cluster-client
  labels:
    app.kubernetes.io/component: aeron-client
  # Additional multus network
  annotations:
    k8s.v1.cni.cncf.io/networks: aeron-network
spec:
  # Creates the /dev/shm/aeron directory for the aeron driver
  initContainers:
    - name: init-container
      image: public.ecr.aws/docker/library/busybox:stable
      command:
        - mkdir
      args:
        - /dev/shm/aeron
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  containers:
    - name: aeronmd-java
      imagePullPolicy: Always
      command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-java-media-driver.sh"]
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      resources:
        limits:
          cpu: "8"
          memory: 8G
    - name: aeron-cluster-client
      env:
        - name: BENCHMARK_TYPE
          value: "aeron-cluster-java"
      command:
        - "k8s/k8s-aeron-cluster-client.sh"
      args:
        - "--output-file"
        - "clusterclientjava"
        - "--message-rate"
        - "101K"
        - "--message-length"
        - "288"
        - "--iterations"
        - "60"
