---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-cluster-client
  labels:
    app.kubernetes.io/component: aeron-client
  # Additional multus network
  annotations:
    k8s.v1.cni.cncf.io/networks: aeron-network
    aeron.io/media-driver: "true"
spec:
  initContainers:
    - name: aeron-bootstrap
      imagePullPolicy: Always
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
        - name: AERON_MD_BOOTSTRAP_PATH
          value: /opt/aeronmd-config/bootstrap.properties
      volumeMounts:
        - name: aeronmd-config
          mountPath: /opt/aeronmd-config
      resources:
        requests:
          cpu: "1"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 256Mi
  containers:
    - name: aeronmd-java
      imagePullPolicy: IfNotPresent
      command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-java-media-driver.sh"]
      args:
        - /opt/aeronmd-config/bootstrap.properties
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: aeronmd-config
          mountPath: /opt/aeronmd-config
      resources:
        requests:
          cpu: "8"
          memory: 8G
        limits:
          cpu: "8"
          memory: 8G
    - name: aeron-cluster-client
      env:
        - name: BENCHMARK_TYPE
          value: "aeron-cluster-java"
      command:
        - "k8s/k8s-aeron-cluster-client.sh"
